version: "2"
checks:
  method-complexity:
    enabled: true
    config:
      threshold: 8
  method-lines:
    enabled: true
    config:
      threshold: 50
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/__tests__/"
  - "**/vendor/"
  - "**/*.d.ts"